version: "3"

services:

  db:
    image: postgres:10-alpine
    env_file: ../db/.env
    volumes:
    - ../db/context/initdb.d:/docker-entrypoint-initdb.d

  legacy:
    image: php:fpm-alpine
    env_file: ../legacy/.env
    volumes:
    - ../legacy/context/:/var/www/html/:ro

  migration:
    image: kamilsk/guard:latest
    build:
      context:    ../../../.
      dockerfile: ./env/docker/service/Dockerfile
    command: [ "migrate" ]
    depends_on:
    - db
    env_file: ../service/.env
    restart: on-failure

  service:
    image: kamilsk/guard:latest
    build:
      context:    ../../../.
      dockerfile: ./env/docker/service/Dockerfile
    command: [ "run", "--with-profiling", "--with-monitoring", "--with-grpc-gateway" ]
    depends_on:
    - migration
    env_file: ../service/.env

  server:
    image: nginx:alpine
    depends_on:
    - legacy
    - service
    env_file: ../server/.env
    volumes:
    - ../server/context/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ../server/context/nginx.conf:/etc/nginx/nginx.conf:ro
