version: "3"

services:

  db:
    ports:
    - ${LOCAL_DB_PORT}:5432
    volumes:
    - ../db/context/initdb.d:/docker-entrypoint-initdb.d
    - pgdata:${PGDATA}

volumes:

  pgdata: { driver: local }
