version: "3"

services:

  db:
    build:
      context:    ../db/context
      dockerfile: ../Dockerfile
    ports:
    - ${LOCAL_DB_PORT}:5432
    volumes:
    - pgdata:${PGDATA}

  legacy:
    build:
      context:    ../legacy/context
      dockerfile: ../Dockerfile

  service:
    build:
      args:       { PACKAGE: "${PACKAGE}" }
      context:    ../../../.
      dockerfile: ./env/docker/service/Dockerfile
    ports:
    - ${LOCAL_SERVICE_HTTP_PORT}:80
    - ${LOCAL_SERVICE_PROFILING_PORT}:8090
    - ${LOCAL_SERVICE_MONITORING_PORT}:8091
    - ${LOCAL_SERVICE_GRPC_PORT}:8092
    - ${LOCAL_SERVICE_GRPC_GATEWAY_PORT}:8093

  server:
    build:
      context:    ../server/context
      dockerfile: ../Dockerfile
    ports:
    - ${LOCAL_SERVER_HTTP_PORT}:80
    - ${LOCAL_SERVER_HTTPS_PORT}:443

volumes:

  pgdata: { driver: local }
