version: "3"

services:

  db:
    image: guard-db:latest
    env_file: ../db/.env

  service:
    image: guard-service:latest
    command: [ "run", "--with-profiling", "--with-monitoring" ]
    depends_on:
    - db
    env_file: ../service/.env

  server:
    image: guard-server:latest
    depends_on:
    - service
    env_file: ../server/.env
