version: "3"

services:

  db:
    image: guard-db:latest
    env_file: ../db/.env

  legacy:
    image: guard-legacy:latest
    env_file: ../legacy/.env

  migration:
    image: guard-service:latest
    command: [ "migrate" ]
    depends_on:
    - db
    env_file: ../service/.env

  service:
    image: guard-service:latest
    command: [ "run", "--with-profiling", "--with-monitoring", "--with-grpc-gateway" ]
    depends_on:
    - migration
    env_file: ../service/.env

  server:
    image: guard-server:latest
    depends_on:
    - legacy
    - service
    env_file: ../server/.env
