version: "3"

services:

  db:
    ports:
    - ${LOCAL_DB_PORT}:5432
    volumes:
    - ../db/context/initdb.d:/docker-entrypoint-initdb.d
    - pgdata:${PGDATA}

  service:
    build:
      args:       { PACKAGE: "${PACKAGE}" }
      context:    ../../../.
      dockerfile: ./env/docker/service/Dockerfile
    ports:
    - ${LOCAL_SERVICE_HTTP_PORT}:80
    - ${LOCAL_SERVICE_PROFILING_PORT}:8090
    - ${LOCAL_SERVICE_MONITORING_PORT}:8091
    - ${LOCAL_SERVICE_GRPC_PORT}:8092

volumes:

  pgdata: { driver: local }
