version: "3"

services:

  db:
    image: guard-db:latest
    build:
      context:    ../db/context
      dockerfile: ../Dockerfile
    env_file: ../db/.env

  legacy:
    image: guard-legacy:latest
    build:
      context:    ../legacy/context
      dockerfile: ../Dockerfile
    env_file: ../legacy/.env

  migration:
    image: kamilsk/guard:latest
    build:
      args:       { PACKAGE: "${PACKAGE}" }
      context:    ../../../.
      dockerfile: ./env/docker/service/Dockerfile
    command: [ "migrate" ]
    depends_on:
    - db
    env_file: ../service/.env
    restart: on-failure

  service:
    image: kamilsk/guard:latest
    build:
      args:       { PACKAGE: "${PACKAGE}" }
      context:    ../../../.
      dockerfile: ./env/docker/service/Dockerfile
    command: [ "run", "--with-profiling", "--with-monitoring", "--with-grpc-gateway" ]
    depends_on:
    - migration
    env_file: ../service/.env

  server:
    image: nginx:alpine
    # build:
    #   context:    ../server/context
    #   dockerfile: ../Dockerfile
    depends_on:
    - legacy
    - service
    env_file: ../server/.env
    volumes:
    - ../server/context/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ../server/context/nginx.conf:/etc/nginx/nginx.conf:ro
