language: go

go:
- master
- 1.x
- 1.10.x
- 1.11.x

matrix:
  fast_finish: true

sudo: false

script:
- make test

after_success:
- echo $TRAVIS_GO_VERSION ":" $TRAVIS_TAG
- if [[ $TRAVIS_GO_VERSION == 1.11* ]] && [ -n "$TRAVIS_TAG" ]; then curl -sL https://git.io/goreleaser | bash; fi
