required = [
  "go.uber.org/zap",

  "go.etcd.io/etcd/clientv3",
  "go.etcd.io/etcd/clientv3/clientv3util",
  "go.etcd.io/etcd/clientv3/concurrency",
  "go.etcd.io/etcd/clientv3/integration",
  "go.etcd.io/etcd/clientv3/leasing",
  "go.etcd.io/etcd/clientv3/mirror",
  "go.etcd.io/etcd/clientv3/namespace",
  "go.etcd.io/etcd/clientv3/naming",
  "go.etcd.io/etcd/clientv3/ordering",
  "go.etcd.io/etcd/clientv3/yaml",

  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options",
  "github.com/grpc-ecosystem/grpc-gateway/utilities",
  "google.golang.org/genproto/googleapis/api/annotations",
]

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "^3.3.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "^1.1.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "^1.5.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/kamilsk/go-kit"
  branch = "master"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.2.0"

[[constraint]]
  name = "go.etcd.io/etcd"
  version = "^3.3.9"

[[constraint]]
  name = "go.uber.org/zap"
  version = "^1.9.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.13.0"

[[constraint]]
  name = "google.golang.org/genproto"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  non-go = false
  unused-packages = false
